from enum import Enum


class TypeId(Enum):
    STOP = "STOP"
    MAJOR_INTERSECTION = "MAJOR_INTERSECTION"
    MINOR_INTERSECTION = "MINOR_INTERSECTION"
    PEDESTRIAN_CROSSING = "PEDESTRIAN_CROSSING"
    RED_LIGHT = "RED_LIGHT"


class CoolingType(Enum):
    AIR = "AIR"
    WATER = "WATER"
    CPM = "CPM"


class Optimisation(Enum):
    THERMAL_COMFORT = "THERMAL_COMFORT"
    BATTERY_TEMPERATURE = "BATTERY_TEMPERATURE"
