@startuml
'https://plantuml.com/use-case-diagram

:Simulator:
(display main page)
(calculate with inputs)

:User:
(Start application) as (start)
(Create new scenario)
(Load scenario)
(Choose cooling system)
(Select environment)

User -> (start)
User --> (Create new scenario)
User --> (Load scenario)
User --> (Choose cooling system)
User --> (Select environment)
User --> Simulator

top to bottom direction
Simulator -> (display main page)
Simulator -> (calculate with inputs)

note left of User : Simulator user.

note left of (Select environment)
Select temperature
Select humidity
end note

@enduml